### ISSUE TITLE
i am getting error like this... how to fix this?

### ISSUE THREAD

**Issue by PreethiRe** [sbanerj1/IrisSeg#1]
if (img[j][i][0]) < min_val:
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Process finished with exit code 1

**Comment by sbanerj1** [comment]
I am looking at this code after 2 years but shouldn't (img[j][i][0]) be typecast to integer before? I mean it should be 'if int(img[j][i][0]) < min_val:'. That is what's in the code it seems. Please let me know if this works :)

**Comment by PreethiRe** [comment]
if int(img[j][i][0]) < min_val:
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices



I am getting like this..

**Comment by sbanerj1** [comment]
I just executed the code on the two example eye images and it worked without any problem. Are you getting the error on any of these images? If not, can you share your image which produces this error?

**Comment by PreethiRe** [comment]
I used these eye images only.. but still getting


 if int(img[j][i][0]) < min_val:
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis
(`None`) and integer or boolean arrays are valid indices

**Comment by sbanerj1** [comment]
Can you print i and j and min_val before the line which causes the error?

**Comment by sbanerj1** [comment]
And please share the full error as is.

**Comment by PreethiRe** [comment]
i have printed i, j and min_val values
if int(img[j][i][0]) < min_val:
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
213.33333333333334 160.0 100

**Comment by sbanerj1** [comment]
Replace lines lines 72 and 73 with:-
h3 = int(h/3)
w3 = int(w/3) 

And let me know if this works.

**Comment by PreethiRe** [comment]
C:\python35\python.exe C:/Users/admin/Downloads/IrisSeg-master/IrisSeg-master/GrabCutIris_LevelSets_Ellipse.py
*** Iris segmentation using GAC and GrabCut (PSIVT Workshops 2015) ***
*** Authors - Sandipan Banerjee & Domingo Mery ***
*** Usage - python GrabCutIris_LevelSets_Ellipse.py <filename> *** 

213 160 100
213 161 100
213 162 100
213 163 100
213 164 100
213 165 100
213 166 100
..........
426 316 25
426 317 25
426 318 25
426 319 25
426 320 25
Traceback (most recent call last):
  File "C:\python35\lib\site-packages\numpy\lib\index_tricks.py", line 166, in __getitem__
    for k in range(len(key)):
TypeError: object of type 'map' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/admin/Downloads/IrisSeg-master/IrisSeg-master/GrabCutIris_LevelSets_Ellipse.py", line 362, in <module>
    test_iris()
  File "C:/Users/admin/Downloads/IrisSeg-master/IrisSeg-master/GrabCutIris_LevelSets_Ellipse.py", line 338, in test_iris
    mgac.levelset = circle_levelset(img_lvl.shape, (cy, cx), (int(max_t/2) + 30))
  File "C:/Users/admin/Downloads/IrisSeg-master/IrisSeg-master/GrabCutIris_LevelSets_Ellipse.py", line 323, in circle_levelset
    grid = np.mgrid[map(slice, shape)].T - center
  File "C:\python35\lib\site-packages\numpy\lib\index_tricks.py", line 208, in __getitem__
    step = key.step
AttributeError: 'map' object has no attribute 'step'

Process finished with exit code 1

**Comment by sbanerj1** [comment]
Looks like a python version issue. I used python 2.7 and it worked fine. So I would recommend you try executing the code with python 2.7. Let me know if it works.

**Comment by PreethiRe** [comment]
i am using python 3.5 i'll try this in python 2.7 and let you know

**Comment by sbanerj1** [comment]
Hi, just wanted to check if the code is now working for you before I close the issue...please let me know in a couple of days.

**Comment by PreethiRe** [comment]
yes it works.. thank you for support but am looking for iris feature
extraction and recognition..

**Comment by sbanerj1** [comment]
Glad to hear. As for iris feature extraction, there should be many resources out there which can help you. Good luck!

**Comment by PreethiRe** [comment]
thank you so much :-)

**Comment by PreethiRe** [comment]
i didn't found any resource for iris feature extraction in python.. if u
did that help me too..

**Comment by sbanerj1** [comment]
Sorry but I never worked on anything past iris segmentation but I am pretty sure you can find some resources, maybe not in Python (like this: http://staffhome.ecm.uwa.edu.au/~00011811/studentprojects/libor/sourcecode.html). You can always write the python version yourself and share. Alternatively you can try using Daugman's method or use general methods like SIFT, etc.

**Comment by PreethiRe** [comment]
thank you
